# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Nexus

on:
  push:
    tags:
      - '*'
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean shadowJar

    - name: Publish to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        PROJECT_VERSION: ${{ github.ref_name }}
      run: ./gradlew publish

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.MODULO_HOST }} >> ~/.ssh/known_hosts

    - name: Deplay Javadoc
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MODULO_HOST }}
        username: debian
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd javadoc/javadoc/
          rm -rf ${{ github.ref_name }}
          mkdir ${{ github.ref_name }}
          cd ${{ github.ref_name }}
          wget 'https://nexus.aytronn.com/repository/aydustries/fr%2Faytronn%2Fmodulo-api%2F${{ github.ref_name }}%2Fmodulo-api-${{ github.ref_name }}-javadoc.jar' -O ${{ github.ref_name }}.jar
          unzip ${{ github.ref_name }}.jar
          rm ${{ github.ref_name }}.jar
