name: Docker Hub

on:
  push:
    tags:
      - '*'
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Login to docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push docker image
        env:
          PROJECT_VERSION: ${{ github.ref_name }}
        run: ./gradlew dockerPushDockerHub
